create table if not exists foundations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    foundationname text,
    address text,
    pnumber text,
    mail text,
    website text,
    contactperson text,
    purpose text,
    kindofboost text,
    sum text,
    currency text,
    broadness text,
    acadDegree text,
    condElse text,
    deadline text,
    variabel text,
    fix text,
    pending text,
    noInfo text,
    resContact text,
    notes text,
    timeContact text,
    lastChange text,
    deleted integer,
    sondierung text
);