create table if not exists foundations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    foundationname text,
    keyword text,
    address text,
    pnumber text,
    mail text,
    website text,
    contactperson text,
    purpose text,
    kindofboost text,
    sum text,
    currency text,
    hitword text,
    groups text,
    broadness text,
    condDoc text,
    condSci text,
    condElse text,
    condAge real,
    condEText text,
    deadline text,
    pending text,
    noInfo text,
    resContact text,
    timeContact text,
    lastChange text
);
